# -*- coding: utf-8 -*-
"""Image Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13aIJ95RX9JMeyNkAb8yI2pCMh8sgngjR
"""

import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from glob import glob
import cv2

from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/Colab Notebooks/Garbage classification'

from keras_preprocessing.image import ImageDataGenerator

# We need augumentation of both train and test but in test we just need to rescale
train_data = ImageDataGenerator(rescale = 1./255,
                                shear_range=0.2,
                                zoom_range=0.2,
                                validation_split=0.2,
                                horizontal_flip=True)

test_gen = ImageDataGenerator(rescale = 1./255,
                              validation_split=0.2)

training_set = train_data.flow_from_directory(path,
                                              batch_size=32,
                                              subset='training',
                                              class_mode = 'categorical',
                                              target_size=(224, 224))
test_set = test_gen.flow_from_directory(path,
                                        batch_size=32,
                                        subset='validation',
                                        class_mode = 'categorical',
                                        target_size=(224, 224))

imgs, labels = next(training_set)

import matplotlib.pyplot as plt
def plot_image(img_array):
  fig, axes = plt.subplots(1, 10, figsize=(20,20))
  axes = axes.flatten()
  for img, ax in zip(img_array, axes):
    ax.imshow(img)
    ax.axis('off')
  plt.tight_layout()
  plt.show()

plot_image(imgs)